# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9081f15d3ac695ad9a0b636f0c790c9d133c09c33123a5140686372e42c85ecc25e4d181e35cdd256a376bdc6c85dc7d81b4b9a0da03bfb304eac21b31b2531b

test:
  secret_key_base: dccff8b84521b69f068989c6f91ec5e9c4051aa0c5ee57bc8884520e89b8dd0dd9f9c01e65378385f9c7aec5808a45ded79a78500742a015b879973bbb12901e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
